[package]
name = "charts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters-backend = { workspace = true }
plotters.workspace = true
image.workspace = true
rand.workspace = true
num-traits.workspace = true
rand_xorshift.workspace = true
rand_distr.workspace = true
